apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: service-c
build:
  artifacts:
  - image: amitb26j/service-c
    jib:
      project: com.serviceb:service-c
  tagPolicy:
    gitCommit: { }
deploy:
  kubectl:
    manifests:
    - k8/deployment.yaml
